FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.13 AS builder

WORKDIR /build
COPY . .
RUN GO111MODULE=on CGO_ENABLED=0 GOOS=${GOOS} GOPROXY=${GOPROXY} go build \
  -ldflags="-w -s -X 'main.version=${VERSION}'" \
  -o=cluster-api-provider-ibmcloud-controller-manager \
  main.go

FROM registry.ci.openshift.org/ocp/4.13:base

LABEL description="Cluster API Provider IBM Cloud Controller Manager"

COPY --from=builder /build/cluster-api-provider-ibmcloud-controller-manager /bin/cluster-api-provider-ibmcloud-controller-manager

ENTRYPOINT [ "/bin/cluster-api-provider-ibmcloud-controller-manager" ]

LABEL io.openshift.release.operator true
